version: '3.7'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    networks:
      - food-ordering-system
    hostname: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    restart: always